version: 0.2

phases:
  install:
    commands:
      - npm i -g heroku
      - npm install -g @angular/cli
      - npm i caniuse-lite@latest
      - npm i jasmine-core@3.5
      - npm install
      - cd backend
      - npm install
      - cd ..
  build:
    commands:
      - cd backend
      - npm test
      - cd ..
      - npm run test